name: Go

on:
  push:
    tags:
      - '*'

      
jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: |
          cd tool
          bash ./build-all-platform.sh
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
          
      
